"""Export endpoints for downloading timetable as Excel."""

from __future__ import annotations

import io

from fastapi import APIRouter
from fastapi.responses import StreamingResponse
from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side

from api.schemas import GenerateRequest
from scheduler.backtracking import solve
from scheduler.graph import build_conflict_graph
from scheduler.parser import parse_input

from .generate import _request_to_raw

router = APIRouter()


@router.post("/export/excel")
def export_excel(req: GenerateRequest) -> StreamingResponse:
    """Generate timetable and return as Excel file."""
    raw = _request_to_raw(req)
    data = parse_input(raw)
    graph, lectures = build_conflict_graph(data)
    timetable, stats = solve(data, graph, lectures, timeout=req.timeout)

    if timetable is None:
        wb = Workbook()
        ws = wb.active
        ws.title = "Error"
        ws["A1"] = "No valid timetable found. Try adjusting constraints."
        buf = io.BytesIO()
        wb.save(buf)
        buf.seek(0)
        return StreamingResponse(
            buf,
            media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            headers={"Content-Disposition": "attachment; filename=timetable_error.xlsx"},
        )

    wb = Workbook()
    wb.remove(wb.active)

    header_font = Font(bold=True, color="FFFFFF", size=11)
    header_fill = PatternFill(start_color="2563EB", end_color="2563EB", fill_type="solid")
    lab_fill = PatternFill(start_color="FEF3C7", end_color="FEF3C7", fill_type="solid")
    border = Border(
        left=Side(style="thin"),
        right=Side(style="thin"),
        top=Side(style="thin"),
        bottom=Side(style="thin"),
    )
    center = Alignment(horizontal="center", vertical="center", wrap_text=True)

    for group_id, group in data.student_groups.items():
        ws = wb.create_sheet(title=group.name)

        # Title
        ws.merge_cells(start_row=1, start_column=1, end_row=1, end_column=1 + len(data.working_days))
        ws.cell(1, 1, f"Timetable: {group.name} (Strength: {group.strength})")
        ws.cell(1, 1).font = Font(bold=True, size=14)

        # Header row
        ws.cell(3, 1, "Period").font = header_font
        ws.cell(3, 1).fill = header_fill
        ws.cell(3, 1).border = border
        for j, day in enumerate(data.working_days, start=2):
            cell = ws.cell(3, j, day)
            cell.font = header_font
            cell.fill = header_fill
            cell.border = border
            cell.alignment = center
            ws.column_dimensions[cell.column_letter].width = 22

        ws.column_dimensions["A"].width = 10

        # Fill grid
        for period in range(1, data.periods_per_day + 1):
            row = 3 + period
            ws.cell(row, 1, f"P{period}").border = border
            ws.cell(row, 1).alignment = center

            for j, day in enumerate(data.working_days, start=2):
                cell_text = ""
                is_lab = False
                for sc in timetable.assignments.values():
                    if (
                        sc.lecture.group_id == group_id
                        and sc.time_slot.day == day
                        and sc.time_slot.period == period
                    ):
                        subject = data.subjects[sc.lecture.subject_id]
                        teacher = data.teachers[sc.lecture.teacher_id]
                        room = data.rooms[sc.room_id]
                        lab_tag = " [LAB]" if sc.lecture.requires_lab else ""
                        cell_text = f"{subject.code}{lab_tag}\n{teacher.name}\n{room.name}"
                        is_lab = sc.lecture.requires_lab
                        break

                cell = ws.cell(row, j, cell_text or "---")
                cell.border = border
                cell.alignment = center
                if is_lab:
                    cell.fill = lab_fill

        # Stats row
        stats_row = 3 + data.periods_per_day + 2
        ws.cell(stats_row, 1, "Generated by Smart Timetable Scheduler")
        ws.cell(stats_row, 1).font = Font(italic=True, color="888888")

    buf = io.BytesIO()
    wb.save(buf)
    buf.seek(0)
    return StreamingResponse(
        buf,
        media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        headers={"Content-Disposition": "attachment; filename=timetable.xlsx"},
    )
